In [1]:
# !pip install growwapi
# !pip install --upgrade growwapi
# !pip install pyarrow fastparquet
# !pip install --upgrade scipy statsmodels
# !pip install scipy==1.10.1 statsmodels==0.14.0

In [2]:
# DATA:
# → Store → Merge → Clean

# SPLIT:
# → Train / Test

# TRAIN (Selection Phase):
# → Correlation (prices)
# → Cointegration
# → Static Hedge Ratio
# → Spread
# → Half-life
# → Select Pairs

# TEST (Trading Phase):
# → Rolling Hedge Ratio
# → Spread
# → Rolling Z-score
# → Signals
# → Positions
# → Returns
# → PnL
# → Portfolio Metrics

In [3]:
import pandas as pd
import numpy as np
import math
from itertools import combinations
import os
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import statsmodels.api as sm
from statsmodels.tsa.stattools import coint
from growwapi import GrowwAPI

In [4]:
API_Key = "eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjI1NjM4NDU1MTQsImlhdCI6MTc3NTQ0NTUxNCwibmJmIjoxNzc1NDQ1NTE0LCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCI1YThlOWU5MC02MGNjLTQ1NDUtODY1Yi0yZmI0MDdhODRhMTNcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiODdlODE1ZjAtZWM5MS00OTU4LWIwNzUtMDg0MWMyMTk2MzNkXCIsXCJkZXZpY2VJZFwiOlwiNTEyN2ZiZjktMTZiMS01NzUzLTk2MjgtOTQyMTQwNGJhZDYwXCIsXCJzZXNzaW9uSWRcIjpcIjlhZjlkYTc1LWFkNGQtNGM3NS1hMjZjLWRkMTc0OThhYTc5MVwiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYkFvc2NJMXRRNzBlTXdSeHhOa1IxMTlSTkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcImF1dGgtdG90cFwiLFwic291cmNlSXBBZGRyZXNzXCI6XCI0OS4yNDguMTAyLjE1OCwxNzIuNzEuMTk4Ljk0LDM1LjI0MS4yMy4xMjNcIixcInR3b0ZhRXhwaXJ5VHNcIjoyNTYzODQ1NTE0NzI0LFwidmVuZG9yTmFtZVwiOlwiZ3Jvd3dBcGlcIn0iLCJpc3MiOiJhcGV4LWF1dGgtcHJvZC1hcHAifQ.bgjJsha_GiSnbd3cu0Gl9chkWYJyD_qhlEJyz1ujdZbxFOHfrnE8yY0NEFYlYuKoK4f4fOGoHt1_zbiu4O1n6Q"
Secret_Key = "g0VR3jBal&rZld$s%faywsSLJsDcCj$R"

In [5]:
access_token = GrowwAPI.get_access_token(api_key=API_Key, secret=Secret_Key)
# Use access_token to initiate GrowwAPI
groww = GrowwAPI(access_token)

Ready to Groww!

In [6]:
symbol_segment_map = {'RELIANCE': 'Oil Gas & Consumable Fuels', 'HDFCBANK': 'Financial Services', 
                      'ICICIBANK': 'Financial Services', 'INFY': 'Information Technology', 'TCS': 'Information Technology',
                      'HINDUNILVR': 'FMCG', 'ITC': 'FMCG', 'BHARTIARTL': 'Telecommunication', 'SBIN': 'Financial Services',
                      'KOTAKBANK': 'Financial Services', 'AXISBANK': 'Financial Services', 'BAJFINANCE': 'Financial Services',
                      'BAJAJFINSV': 'Financial Services', 'HCLTECH': 'Information Technology', 
                      'WIPRO': 'Information Technology', 'LTIM': 'Information Technology', 'TECHM': 'Information Technology',
                      'LT': 'Construction', 'ULTRACEMCO': 'Construction Materials', 'GRASIM': 'Construction Materials', 
                      'SHREECEM': 'Construction Materials', 'TATASTEEL': 'Metals & Mining', 'JSWSTEEL': 'Metals & Mining', 
                      'HINDALCO': 'Metals & Mining', 'COALINDIA': 'Oil Gas & Consumable Fuels', 
                      'ONGC': 'Oil Gas & Consumable Fuels', 'POWERGRID': 'Power', 'NTPC': 'Power', 
                      'ADANIENT': 'Diversified', 'ADANIPORTS': 'Services', 'ASIANPAINT': 'Consumer Durables', 
                      'TITAN': 'Consumer Durables', 'NESTLEIND': 'FMCG', 'BRITANNIA': 'FMCG', 'MARUTI': 'Automobile', 
                      'M&M': 'Automobile', 'TATAMOTORS': 'Automobile', 'BAJAJ-AUTO': 'Automobile', 
                      'HEROMOTOCO': 'Automobile', 'EICHERMOT': 'Automobile', 'APOLLOHOSP': 'Healthcare', 
                      'SUNPHARMA': 'Healthcare', 'DRREDDY': 'Healthcare', 'CIPLA': 'Healthcare', 'DIVISLAB': 'Healthcare', 
                      'UPL': 'Chemicals', 'SBILIFE': 'Financial Services', 'HDFCLIFE': 'Financial Services', 
                      'SBICARD': 'Financial Services', 'INDUSINDBK': 'Financial Services'}

# -------------------------------------------ETL-------------------------------------------

### Historical Data Storing

In [7]:
def get_historical_data(start_date, end_date, symbol="RELIANCE"):
    historical_data_response = groww.get_historical_candles(
        groww_symbol=f"NSE-{symbol.upper()}",
        exchange=groww.EXCHANGE_NSE,
        segment=groww.SEGMENT_CASH,
        start_time=start_date,
        end_time=end_date,
        candle_interval=groww.CANDLE_INTERVAL_DAY # Optional: Interval in days for the candle data
    )
    return historical_data_response

In [8]:
def fetch_and_store_hist_data(symbol):    
    file_path = os.path.join(os.getcwd(), f"{symbol}_Hist_Data.csv")
    
    if os.path.exists(file_path):
        print(f"Data already exists for {symbol}")
        
    else:
        start_date = pd.to_datetime('2020-01-01')
        end_date = pd.to_datetime('2026-01-01')
        total_days = end_date - start_date
        data_list = []
        while total_days > timedelta(days=0):
            intermediate_end_date = start_date + timedelta(days=180) if total_days > timedelta(days=180) else start_date + timedelta(days=total_days.days)
            print(start_date, " => ", intermediate_end_date)
            hist_data = get_historical_data(start_date, intermediate_end_date, symbol)
            print(hist_data["candles"], '\n\n')
            if hist_data["candles"]:
                data_list.append(hist_data["candles"])
            start_date = intermediate_end_date
            total_days = total_days - timedelta(days=180)
        #     print(total_days, '\n')

        data_list = np.concatenate(data_list)
        data_list

        df = pd.DataFrame(
            data_list,
            columns=["Date", "Open", "High", "Low", "Close", "Volume", "Extra"]
        )

        df.to_csv(f"{symbol}_Hist_Data.csv")

In [9]:
# stock_df = fetch_and_store_hist_data("LTIM")
# stock_df

### Data Merging

In [10]:
df_list = []
for symbol in symbol_segment_map.keys():
    df = pd.read_csv(f"{symbol}_Hist_Data.csv")
    df["Date"] = pd.to_datetime(df["Date"])
    df.set_index("Date", inplace=True)
    
    # remove duplicate dates
    df = df[~df.index.duplicated(keep="first")]
    
    new_df = df["Close"].rename(symbol)
    df_list.append(new_df)


merged_df = pd.concat(df_list, axis=1)
merged_df.to_csv("Merged_Data.csv")

In [11]:
# merged_df

### Data Cleaning

In [12]:
merged_df = pd.read_csv("Merged_Data.csv", index_col="Date", parse_dates=True)
merged_df = merged_df.ffill()
merged_df = merged_df.dropna()

In [13]:
for col in merged_df.columns:
    col_value_count = merged_df[col].notna().sum()
    if col_value_count < 1490:
        print(col, " => ", col_value_count)

RELIANCE  =>  764
HDFCBANK  =>  764
ICICIBANK  =>  764
INFY  =>  764
TCS  =>  764
HINDUNILVR  =>  764
ITC  =>  764
BHARTIARTL  =>  764
SBIN  =>  764
KOTAKBANK  =>  764
AXISBANK  =>  764
BAJFINANCE  =>  764
BAJAJFINSV  =>  764
HCLTECH  =>  764
WIPRO  =>  764
LTIM  =>  764
TECHM  =>  764
LT  =>  764
ULTRACEMCO  =>  764
GRASIM  =>  764
SHREECEM  =>  764
TATASTEEL  =>  764
JSWSTEEL  =>  764
HINDALCO  =>  764
COALINDIA  =>  764
ONGC  =>  764
POWERGRID  =>  764
NTPC  =>  764
ADANIENT  =>  764
ADANIPORTS  =>  764
ASIANPAINT  =>  764
TITAN  =>  764
NESTLEIND  =>  764
BRITANNIA  =>  764
MARUTI  =>  764
M&M  =>  764
TATAMOTORS  =>  764
BAJAJ-AUTO  =>  764
HEROMOTOCO  =>  764
EICHERMOT  =>  764
APOLLOHOSP  =>  764
SUNPHARMA  =>  764
DRREDDY  =>  764
CIPLA  =>  764
DIVISLAB  =>  764
UPL  =>  764
SBILIFE  =>  764
HDFCLIFE  =>  764
SBICARD  =>  764
INDUSINDBK  =>  764

In [14]:
# merged_df.drop(["LTIM", "TATAMOTORS", "SBICARD"], axis=1, inplace=True)

In [15]:
merged_df = merged_df.ffill()

In [16]:
train_df = merged_df.loc[:'2023-12-31']
test_df = merged_df.loc['2024-01-01':]

# -------------------------------------------Training Data Analysis--------------------------------------

### Correlation

In [17]:
corr_matrix = train_df.corr()
corr_matrix

,RELIANCE,HDFCBANK,ICICIBANK,INFY,TCS,HINDUNILVR,ITC,BHARTIARTL,SBIN,KOTAKBANK,...,APOLLOHOSP,SUNPHARMA,DRREDDY,CIPLA,DIVISLAB,UPL,SBILIFE,HDFCLIFE,SBICARD,INDUSINDBK
RELIANCE,1.000000,0.529197,0.421881,0.025537,0.072152,0.697102,0.129482,0.125121,0.613280,0.627471,...,0.319430,0.021891,0.023815,0.124479,0.432162,0.105651,0.312426,0.426262,0.552649,0.229718
HDFCBANK,0.529197,1.000000,0.106740,-0.032395,-0.060543,0.432206,-0.048551,-0.299640,0.212714,0.615149,...,-0.150406,-0.282586,-0.239513,-0.357865,-0.088511,0.493826,-0.205332,-0.120639,0.248489,-0.259201
ICICIBANK,0.421881,0.106740,1.000000,-0.187570,0.507140,0.132829,0.771389,0.770932,0.702912,0.467131,...,0.810897,0.667343,0.763340,0.609314,0.816965,-0.656264,0.711707,0.798863,0.509413,0.833589
INFY,0.025537,-0.032395,-0.187570,1.000000,0.576641,-0.066110,-0.451966,0.100772,0.160068,-0.411218,...,-0.025937,0.254342,-0.098627,0.352407,-0.095091,0.131467,0.215028,-0.026243,-0.492180,0.019985
TCS,0.072152,-0.060543,0.507140,0.576641,1.000000,-0.157334,0.357594,0.702005,0.486665,-0.122332,...,0.601058,0.770745,0.570407,0.688869,0.488628,-0.516010,0.666235,0.522493,-0.136498,0.668861
HINDUNILVR,0.697102,0.432206,0.132829,-0.066110,-0.157334,1.000000,-0.033883,-0.082527,0.352171,0.576568,...,0.077632,-0.239981,-0.280622,-0.139541,0.192992,0.305404,0.080763,0.182683,0.546079,-0.000921
ITC,0.129482,-0.048551,0.771389,-0.451966,0.357594,-0.033883,1.000000,0.651619,0.227011,0.234730,...,0.740398,0.541987,0.796310,0.357813,0.607693,-0.731279,0.455630,0.612848,0.456250,0.707191
BHARTIARTL,0.125121,-0.299640,0.770932,0.100772,0.702005,-0.082527,0.651619,1.000000,0.561440,0.002589,...,0.922926,0.907263,0.822614,0.800876,0.780471,-0.824271,0.887556,0.827540,0.049656,0.936003
SBIN,0.613280,0.212714,0.702912,0.160068,0.486665,0.352171,0.227011,0.561440,1.000000,0.505522,...,0.572746,0.469187,0.306485,0.516195,0.687089,-0.267949,0.673215,0.662712,0.347236,0.630546
KOTAKBANK,0.627471,0.615149,0.467131,-0.411218,-0.122332,0.576568,0.234730,0.002589,0.505522,1.000000,...,0.152498,-0.177772,-0.069385,-0.181978,0.280800,0.189498,0.043702,0.178614,0.636726,0.075325
AXISBANK,0.232179,-0.196458,0.790932,0.111867,0.670230,0.052043,0.558140,0.926135,0.701866,0.094049,...,0.880389,0.841376,0.709405,0.768270,0.806082,-0.731571,0.916423,0.853097,0.141029,0.919460
BAJFINANCE,0.230156,-0.281917,0.797464,-0.091729,0.546869,0.065729,0.764597,0.827340,0.530419,0.130943,...,0.827919,0.668653,0.758159,0.675510,0.788861,-0.742944,0.725682,0.807555,0.416377,0.881634
BAJAJFINSV,0.424840,-0.145311,0.767116,0.165649,0.601570,0.178370,0.503401,0.881528,0.730698,0.197774,...,0.872005,0.729421,0.632450,0.733412,0.773556,-0.605547,0.863597,0.835174,0.216838,0.861463
HCLTECH,-0.075208,-0.273259,0.607621,0.232186,0.811356,-0.220290,0.583051,0.873325,0.393395,-0.147127,...,0.787689,0.864504,0.734441,0.692858,0.568897,-0.764733,0.769319,0.636798,-0.127099,0.819813
WIPRO,0.337689,0.154692,0.604189,0.483162,0.860421,0.067926,0.374030,0.591566,0.600276,0.120882,...,0.566758,0.645168,0.521950,0.649027,0.583211,-0.406247,0.626729,0.551841,0.176521,0.637368
LTIM,0.037001,-0.194083,0.703716,0.128557,0.746455,-0.163034,0.721177,0.849336,0.360264,-0.055288,...,0.835722,0.805763,0.785424,0.644765,0.588366,-0.774925,0.707564,0.643668,0.069091,0.822567
TECHM,0.059094,-0.218608,0.679985,0.145488,0.703021,-0.250542,0.714874,0.759682,0.295467,-0.143327,...,0.745006,0.774419,0.829956,0.645617,0.620289,-0.747868,0.640774,0.653772,0.095447,0.760585
LT,-0.084565,-0.326138,0.709794,0.102345,0.746826,-0.303757,0.657326,0.937415,0.437415,-0.129366,...,0.836569,0.928904,0.865790,0.769586,0.675584,-0.852354,0.803105,0.715175,-0.095115,0.881194
ULTRACEMCO,0.120266,-0.097677,0.803412,-0.073524,0.632912,-0.084496,0.776447,0.876293,0.468129,0.113677,...,0.885646,0.824467,0.814704,0.613453,0.668498,-0.795773,0.755285,0.717002,0.123254,0.859728
GRASIM,0.128104,-0.231250,0.808178,0.089704,0.689613,-0.109148,0.593851,0.953449,0.623760,0.106628,...,0.873735,0.879581,0.800743,0.786773,0.768916,-0.754915,0.861237,0.782796,0.051609,0.894784
SHREECEM,-0.258854,-0.235218,0.346135,0.148521,0.522139,-0.320463,0.378554,0.575276,0.127663,-0.163977,...,0.513484,0.515681,0.407706,0.272763,0.158447,-0.441907,0.386198,0.199934,-0.231025,0.442117
TATASTEEL,0.056135,-0.214465,0.589563,0.391644,0.825285,-0.185381,0.403791,0.811173,0.545021,-0.163972,...,0.696881,0.890269,0.712584,0.839392,0.712299,-0.656923,0.842366,0.742018,-0.100568,0.798478
JSWSTEEL,0.471817,0.118593,0.797381,0.180055,0.674754,0.114451,0.548307,0.786374,0.697172,0.180797,...,0.805923,0.812936,0.754524,0.784959,0.836560,-0.595896,0.853190,0.858185,0.226862,0.831993
HINDALCO,0.139904,-0.100052,0.488036,0.490022,0.781621,-0.098923,0.154528,0.737708,0.640462,-0.043327,...,0.609576,0.817021,0.521388,0.773002,0.603740,-0.489764,0.808656,0.615334,-0.248005,0.686371
COALINDIA,-0.161472,-0.389454,0.555467,0.137763,0.673020,-0.289869,0.474155,0.886011,0.408651,-0.107512,...,0.747835,0.826097,0.663325,0.658402,0.534440,-0.742971,0.745655,0.580610,-0.236074,0.777350
ONGC,-0.117817,-0.347573,0.714225,-0.038823,0.663310,-0.375989,0.720148,0.885203,0.366154,-0.091041,...,0.796712,0.875066,0.877400,0.714168,0.644474,-0.898124,0.729753,0.675892,-0.038609,0.863179
POWERGRID,0.483053,0.553930,0.319871,-0.484423,-0.258949,0.366151,0.381256,-0.132049,0.087897,0.502927,...,0.118193,-0.142329,0.103954,-0.198978,0.133879,0.028847,-0.083965,0.126787,0.567865,0.005770
NTPC,-0.063022,-0.304080,0.701268,0.155336,0.759264,-0.305801,0.616258,0.923493,0.446960,-0.141670,...,0.825817,0.929195,0.840011,0.772189,0.648360,-0.838756,0.797854,0.691025,-0.108400,0.864723
ADANIENT,0.535756,0.072909,0.177377,0.386217,0.131630,0.433380,-0.379605,0.169122,0.690426,0.208527,...,0.123622,0.148159,-0.115854,0.377765,0.402365,0.128718,0.443796,0.384739,0.130528,0.207359
ADANIPORTS,0.345422,-0.092804,0.698815,0.224994,0.553893,0.056042,0.262761,0.750779,0.798429,0.160108,...,0.689064,0.701544,0.529048,0.702163,0.693258,-0.501610,0.808849,0.708169,0.089015,0.736310
ASIANPAINT,0.630355,0.107732,0.861235,-0.187707,0.359496,0.379150,0.696403,0.659970,0.688421,0.456855,...,0.801797,0.509837,0.613271,0.515398,0.826620,-0.534667,0.659772,0.817019,0.644641,0.756956
TITAN,0.099587,-0.265294,0.826383,-0.065851,0.643260,-0.115311,0.780905,0.953845,0.497953,0.058688,...,0.921754,0.869414,0.880219,0.734182,0.775637,-0.865005,0.830777,0.818308,0.143835,0.933161
NESTLEIND,0.177760,-0.219851,0.823025,-0.233196,0.518004,0.017134,0.786429,0.906742,0.531770,0.216297,...,0.903493,0.778367,0.806084,0.649947,0.789197,-0.827226,0.805667,0.816813,0.241646,0.909672
BRITANNIA,0.499766,0.244727,0.664767,-0.169757,0.412986,0.406541,0.723158,0.620253,0.474946,0.395325,...,0.795049,0.466351,0.493710,0.296877,0.571391,-0.453251,0.564879,0.635104,0.406540,0.642239
MARUTI,-0.037654,-0.403620,0.729820,-0.058581,0.626637,-0.157235,0.781664,0.900547,0.373001,-0.045134,...,0.842537,0.809633,0.843132,0.716223,0.730073,-0.860507,0.768974,0.774739,0.168240,0.901341
M&M,0.175771,-0.208494,0.750363,0.174036,0.782033,-0.066710,0.705183,0.894424,0.497495,-0.062498,...,0.862411,0.901014,0.862393,0.825715,0.778625,-0.817168,0.858396,0.840412,0.133355,0.925230
TATAMOTORS,0.093472,-0.229601,0.824775,-0.148695,0.623459,-0.106891,0.869537,0.914800,0.424089,0.067310,...,0.906898,0.852484,0.910768,0.694600,0.765882,-0.891983,0.780302,0.807391,0.216349,0.924743
BAJAJ-AUTO,0.015465,-0.205198,0.758544,-0.137027,0.620168,-0.147140,0.782907,0.905695,0.419536,0.101750,...,0.874799,0.820980,0.809172,0.597325,0.662909,-0.829562,0.743120,0.702791,0.067893,0.857408
HEROMOTOCO,0.256771,-0.108392,0.749936,0.168518,0.742272,0.058766,0.573415,0.933349,0.647144,0.102495,...,0.894405,0.884242,0.720709,0.745735,0.757334,-0.731963,0.901783,0.814308,0.050197,0.894788
EICHERMOT,0.202386,-0.030468,0.691763,-0.043634,0.572068,0.140636,0.555264,0.774665,0.550895,0.332603,...,0.781938,0.623565,0.521258,0.499590,0.612261,-0.561188,0.704834,0.615923,0.221819,0.734574
APOLLOHOSP,0.319430,-0.150406,0.810897,-0.025937,0.601058,0.077632,0.740398,0.922926,0.572746,0.152498,...,1.000000,0.809522,0.786541,0.692786,0.797138,-0.759724,0.841253,0.840855,0.238486,0.906259
SUNPHARMA,0.021891,-0.282586,0.667343,0.254342,0.770745,-0.239981,0.541987,0.907263,0.469187,-0.177772,...,0.809522,1.000000,0.860190,0.881823,0.718846,-0.823461,0.865302,0.774390,-0.127938,0.875225
DRREDDY,0.023815,-0.239513,0.763340,-0.098627,0.570407,-0.280622,0.796310,0.822614,0.306485,-0.069385,...,0.786541,0.860190,1.000000,0.762491,0.736614,-0.867529,0.702630,0.747944,0.127666,0.840393
CIPLA,0.124479,-0.357865,0.609314,0.352407,0.688869,-0.139541,0.357813,0.800876,0.516195,-0.181978,...,0.692786,0.881823,0.762491,1.000000,0.745855,-0.733394,0.855499,0.770547,0.008392,0.832610
DIVISLAB,0.432162,-0.088511,0.816965,-0.095091,0.488628,0.192992,0.607693,0.780471,0.687089,0.280800,...,0.797138,0.718846,0.736614,0.745855,1.000000,-0.652125,0.827299,0.927582,0.432272,0.852049
UPL,0.105651,0.493826,-0.656264,0.131467,-0.516010,0.305404,-0.731279,-0.824271,-0.267949,0.189498,...,-0.759724,-0.823461,-0.867529,-0.733394,-0.652125,1.000000,-0.699853,-0.700314,-0.080995,-0.861447
SBILIFE,0.312426,-0.205332,0.711707,0.215028,0.666235,0.080763,0.455630,0.887556,0.673215,0.043702,...,0.841253,0.865302,0.702630,0.855499,0.827299,-0.699853,1.000000,0.918693,0.095910,0.903435
HDFCLIFE,0.426262,-0.120639,0.798863,-0.026243,0.522493,0.182683,0.612848,0.827540,0.662712,0.178614,...,0.840855,0.774390,0.747944,0.770547,0.927582,-0.700314,0.918693,1.000000,0.335630,0.896745
SBICARD,0.552649,0.248489,0.509413,-0.492180,-0.136498,0.546079,0.456250,0.049656,0.347236,0.636726,...,0.238486,-0.127938,0.127666,0.008392,0.432272,-0.080995,0.095910,0.335630,1.000000,0.249324
INDUSINDBK,0.229718,-0.259201,0.833589,0.019985,0.668861,-0.000921,0.707191,0.936003,0.630546,0.075325,...,0.906259,0.875225,0.840393,0.832610,0.852049,-0.861447,0.903435,0.896745,0.249324,1.000000

In [18]:
# plt.figure(figsize=(20,16))
# sns.heatmap(corr_matrix)

In [19]:
# corr_matrix.columns

In [20]:
# Create stocks pairs

stocks = merged_df.columns
pairs = list(combinations(stocks, 2))
# pairs

In [21]:
cross_sector_pairs = []
for s1, s2 in pairs:
    if symbol_segment_map[s1] != symbol_segment_map[s2]:
        cross_sector_pairs.append((s1, s2))

# cross_sector_pairs

In [22]:
correlated_pairs = []

for s1, s2 in cross_sector_pairs:
    corr = corr_matrix.loc[s1, s2]
    
    if abs(corr) > 0.3:
        correlated_pairs.append((s1, s2, round(corr, 2)))
    
# correlated_pairs

In [23]:
correlated_pairs_df = pd.DataFrame(correlated_pairs, columns=["Stock1", "Stock2", "Corr_Value"])
correlated_pairs_df.sort_values(by="Corr_Value", ascending=False)

         Stock1      Stock2  Corr_Value
448          LT        NTPC        0.98
727       TITAN  TATAMOTORS        0.96
447          LT        ONGC        0.96
483  ULTRACEMCO  BAJAJ-AUTO        0.95
636        ONGC        NTPC        0.95
..          ...         ...         ...
847         UPL  INDUSINDBK       -0.86
832     DRREDDY         UPL       -0.87
736       TITAN         UPL       -0.87
793  TATAMOTORS         UPL       -0.89
653        ONGC         UPL       -0.90

[848 rows x 3 columns]

In [24]:
# heatmap_matrix = correlated_pairs_df.pivot(index="Stock1", columns="Stock2", values="Corr_Value")
# heatmap_matrix

In [25]:
# plt.figure(figsize=(10,6))

# sns.heatmap(
#     heatmap_matrix,
#     cmap="coolwarm",
#     annot=True,
#     linewidths=0.5
# )

In [26]:
cointegrated_pairs = []

for s1, s2, corr in correlated_pairs:
    
    coint_pair = train_df[[s1, s2]].copy()
    coint_pair = coint_pair.replace([-np.inf, np.inf], np.nan).dropna()
    score, p_value, _ = coint(merged_df[s1], merged_df[s2])
    
    if len(coint_pair) < 100:
        continue
    
    if p_value < 0.03 and score < -3:
        cointegrated_pairs.append((s1, s2, corr, score, p_value))

# cointegrated_pairs

In [27]:
cointegrated_pairs_df = pd.DataFrame(cointegrated_pairs, columns=["Stock1", "Stock2", "Corr_Score", "CoIn_Score", "P_Value"])
cointegrated_pairs_df.sort_values("P_Value")

        Stock1      Stock2  Corr_Score  CoIn_Score   P_Value
0   BHARTIARTL    JSWSTEEL        0.79   -4.607428  0.000811
10    JSWSTEEL   EICHERMOT        0.60   -4.520441  0.001133
9     JSWSTEEL         M&M        0.85   -4.221721  0.003381
14   BRITANNIA     SBILIFE        0.56   -4.208898  0.003536
6   ULTRACEMCO  APOLLOHOSP        0.89   -4.150381  0.004332
4   BAJAJFINSV    JSWSTEEL        0.79   -4.022571  0.006667
8    TATASTEEL  ADANIPORTS        0.68   -4.020674  0.006709
3     AXISBANK  ADANIPORTS        0.84   -3.960996  0.008156
2     AXISBANK   TATASTEEL        0.82   -3.863717  0.011123
1         SBIN    HINDALCO        0.64   -3.770222  0.014846
7       GRASIM  APOLLOHOSP        0.87   -3.759034  0.015358
5           LT       TITAN        0.94   -3.661965  0.020493
11    ADANIENT  ADANIPORTS        0.62   -3.633592  0.022251
13  ADANIPORTS  HEROMOTOCO        0.77   -3.607496  0.023983
12    ADANIENT       CIPLA        0.38   -3.553161  0.027965

### Hedge Ratio

In [28]:
def get_hedge_ratio(y, x):
    x = sm.add_constant(x)
    model = sm.OLS(y, x).fit()
#     print(x, y, model.params, "\n")
    beta = model.params.iloc[1]
    return beta

In [29]:
hedge_ratio = {}
for s1, s2, corr, coin, _ in cointegrated_pairs:
    if not hedge_ratio.get(s1):
        hedge_ratio[s1] = {}
        
    hedge_ratio[s1][s2] = get_hedge_ratio(train_df[s2], train_df[s1])

In [30]:
hedge_ratio

{'BHARTIARTL': {'JSWSTEEL': 0.49618669236312585},
 'SBIN': {'HINDALCO': 0.8822213807856469},
 'AXISBANK': {'TATASTEEL': 0.09913874453990296,
  'ADANIPORTS': 1.3023138375063283},
 'BAJAJFINSV': {'JSWSTEEL': 0.3053129681165867},
 'LT': {'TITAN': 0.8612574634866541},
 'ULTRACEMCO': {'APOLLOHOSP': 0.4613948698150707},
 'GRASIM': {'APOLLOHOSP': 2.465683370177081},
 'TATASTEEL': {'ADANIPORTS': 8.729932521477286},
 'JSWSTEEL': {'M&M': 2.767088319313693, 'EICHERMOT': 3.3547088201766604},
 'ADANIENT': {'ADANIPORTS': 0.10962113451131487, 'CIPLA': 0.07404154477773796},
 'ADANIPORTS': {'HEROMOTOCO': 2.666355948217271},
 'BRITANNIA': {'SBILIFE': 0.22052330531090278}}

### Spread

In [31]:
spread = {}
for s1, s2, corr, coin, _ in cointegrated_pairs:
    if not spread.get(s1):0
    spread[s1] = {}
    spread[s1][s2] = merged_df[s1] - hedge_ratio[s1][s2] * merged_df[s2]

In [32]:
spread

{'BHARTIARTL': {'JSWSTEEL': Date
  2022-12-05     468.685149
  2022-12-06     462.822587
  2022-12-07     467.739793
  2022-12-08     463.089770
  2022-12-09     467.523373
                   ...
  2025-12-26    1562.373284
  2025-12-29    1539.466420
  2025-12-30    1548.238873
  2025-12-31    1527.641741
  2026-01-01    1529.117290
  Length: 764, dtype: float64},
 'SBIN': {'HINDALCO': Date
  2022-12-05    192.775072
  2022-12-06    194.305951
  2022-12-07    197.434613
  2022-12-08    195.550286
  2022-12-09    208.163834
                   ...
  2025-12-26    196.208957
  2025-12-29    201.928506
  2025-12-30    193.433966
  2025-12-31    199.934302
  2026-01-01    195.205975
  Length: 764, dtype: float64},
 'AXISBANK': {'ADANIPORTS': Date
  2022-12-05   -263.961604
  2022-12-06   -262.809240
  2022-12-07   -240.176795
  2022-12-08   -223.486026
  2022-12-09   -226.336051
                   ...
  2025-12-26   -708.470908
  2025-12-29   -662.085245
  2025-12-30   -656.940979
  2025-12-31   -644.740878
  2026-01-01   -654.457025
  Length: 764, dtype: float64},
 'BAJAJFINSV': {'JSWSTEEL': Date
  2022-12-05    1403.200208
  2022-12-06    1407.257541
  2022-12-07    1381.333233
  2022-12-08    1391.233433
  2022-12-09    1372.546278
                   ...
  2025-12-26    1683.465488
  2025-12-29    1678.515051
  2025-12-30    1687.014105
  2025-12-31    1684.271455
  2026-01-01    1679.325858
  Length: 764, dtype: float64},
 'LT': {'TITAN': Date
  2022-12-05   -167.148084
  2022-12-06   -160.410782
  2022-12-07   -112.556444
  2022-12-08    -57.358657
  2022-12-09    -98.525833
                   ...
  2025-12-26    609.160206
  2025-12-29    607.708643
  2025-12-30    629.276714
  2025-12-31    594.115387
  2026-01-01    652.910153
  Length: 764, dtype: float64},
 'ULTRACEMCO': {'APOLLOHOSP': Date
  2022-12-05    4993.893824
  2022-12-06    5032.868294
  2022-12-07    4981.001892
  2022-12-08    5008.417835
  2022-12-09    4915.718895
                   ...
  2025-12-26    8492.258312
  2025-12-29    8530.248045
  2025-12-30    8479.849860
  2025-12-31    8534.626629
  2026-01-01    8619.790383
  Length: 764, dtype: float64},
 'GRASIM': {'APOLLOHOSP': Date
  2022-12-05    -9965.748132
  2022-12-06    -9979.765261
  2022-12-07    -9848.071564
  2022-12-08    -9787.357415
  2022-12-09    -9752.073158
                    ...
  2025-12-26   -14826.730197
  2025-12-29   -14625.733836
  2025-12-30   -14393.426758
  2025-12-31   -14535.575134
  2026-01-01   -14683.007287
  Length: 764, dtype: float64},
 'TATASTEEL': {'ADANIPORTS': Date
  2022-12-05    -7681.289232
  2022-12-06    -7712.998009
  2022-12-07    -7630.067663
  2022-12-08    -7683.106748
  2022-12-09    -7665.737394
                    ...
  2025-12-26   -12813.162653
  2025-12-29   -12524.513859
  2025-12-30   -12580.377400
  2025-12-31   -12651.174820
  2026-01-01   -12748.013058
  Length: 764, dtype: float64},
 'JSWSTEEL': {'EICHERMOT': Date
  2022-12-05   -10462.888178
  2022-12-06   -10322.782694
  2022-12-07   -10197.697547
  2022-12-08   -10400.649113
  2022-12-09   -10525.383160
                    ...
  2025-12-26   -23475.487399
  2025-12-29   -23302.842540
  2025-12-30   -23017.143189
  2025-12-31   -23366.508248
  2026-01-01   -23478.900411
  Length: 764, dtype: float64},
 'ADANIENT': {'CIPLA': Date
  2022-12-05    3847.817763
  2022-12-06    3949.643502
  2022-12-07    3917.461881
  2022-12-08    3942.998989
  2022-12-09    3914.769373
                   ...
  2025-12-26    2118.393434
  2025-12-29    2092.581932
  2025-12-30    2104.192994
  2025-12-31    2127.801013
  2026-01-01    2148.871045
  Length: 764, dtype: float64},
 'ADANIPORTS': {'HEROMOTOCO': Date
  2022-12-05    -6646.371397
  2022-12-06    -6566.147028
  2022-12-07    -6471.192557
  2022-12-08    -6461.442976
  2022-12-09    -6445.728392
                    ...
  2025-12-26   -13543.148480
  2025-12-29   -13386.537208
  2025-12-30   -13766.358820
  2025-12-31   -13917.740177
  2026-01-01   -14094.418272
  Length: 764, dtype: float64},
 'BRITANNIA': {'SBILIFE': Date
  2022-12-05    4120.076788
  2022-12-06    4140.955500
  2022-12-07    4115.238563
  2022-12-08    4115.530051
  2022-12-09    4130.312585
                   ...
  2025-12-26    5587.241394
  2025-12-29    5598.292261
  2025-12-30    5572.945744
  2025-12-31    5582.257126
  2026-01-01    5559.544248
  Length: 764, dtype: float64}}

### Half Life

In [ ]:
def calculate_half_life(stock_1, stock_2, beta_val):
    
    spread = merged_df[stock_1] - beta_val * merged_df[stock_2]
    
    spread_lag = spread.shift(1)
    spread_return = spread - spread_lag
    
    spread_lag = spread_lag.dropna()
    spread_return = spread_return.dropna()
    
    spread_lag = sm.add_constant(spread_lag)
    
    model = sm.OLS(spread_return, spread_lag).fit()
    
    beta = model.params.iloc[1]
    
    half_life = -np.log(2) / beta
    
    return half_life

In [ ]:
half_lives = []
for _, row in cointegrated_pairs_df.iterrows():
    stock_1 = row["Stock1"]
    stock_2 = row["Stock2"]
    beta_val = hedge_ratio[stock_1][stock_2]
    half_life = calculate_half_life(stock_1, stock_2, beta_val)
    half_lives.append(half_life)

cointegrated_pairs_df["Half_Life"] = half_lives

### Z Score

In [34]:
z_score = {}
for s1, s2, corr, coin, _ in cointegrated_pairs:
    if not z_score.get(s1):
        z_score[s1] = {}
    z_score[s1][s2] = (spread[s1][s2] - spread[s1][s2].mean()) / spread[s1][s2].std()

KeyError: 'TATASTEEL'

In [ ]:
z_score

In [ ]:
# cointegrated_pairs_df[(cointegrated_pairs_df["Stock1"] == "SBIN") & (cointegrated_pairs_df["Stock2"] == "HINDALCO")]["P_Value"].values[0]

In [ ]:
cointegrated_pairs_df.sort_values(by="Half_Life")

In [ ]:
cointegrated_pairs_df

### Rolling Spread and Z-Score

In [ ]:
rolling_z_score = {}
window = 30
for s1, s2, corr, coin, p_value in cointegrated_pairs:
    if not rolling_z_score.get(s1):
        rolling_z_score[s1] = {}
    _spread = spread[s1][s2]
    rolling_mean = _spread.rolling(window).mean()
    rolling_std = _spread.rolling(window).std()
    rolling_z_score[s1][s2] = (_spread - rolling_mean) / rolling_std

In [ ]:
rolling_z_score

In [ ]:
df_list = []

for stock1, inner_dict in rolling_z_score.items():
    for stock2, series in inner_dict.items():
        col_name = f"{stock1}_{stock2}"
        df_list.append(series.rename(col_name))

rolling_z_score_df = pd.concat(df_list, axis=1)

In [ ]:
rolling_z_score_df

### Signal Generation

In [ ]:
entry_threshold = 2
exit_threshold = 0.5
stop_loss = 3

signals_df = pd.DataFrame(index=rolling_z_score_df.index)

for col in rolling_z_score_df.columns:
    
    signals = []
    
    z_series = rolling_z_score_df[col]
    
    for i in range(len(z_series)):
        
        if i == 0 or pd.isna(z_series.iloc[i]):
            signals.append(None)
            continue
        
        prev_z = z_series.iloc[i-1]
        curr_z = z_series.iloc[i]
        
        # LONG ENTRY
        if prev_z < entry_threshold and curr_z > entry_threshold:
            signals.append(1)
        
        # SHORT ENTRY
        elif prev_z > -entry_threshold and curr_z < -entry_threshold:
            signals.append(-1)
        
        # EXIT
        elif abs(curr_z) < exit_threshold:
            signals.append(0)
        
        # STOP LOSS
        elif abs(curr_z) > stop_loss:
            signals.append(0)
        
        else:
            signals.append(None)
    
    signals_df[col] = signals

In [ ]:
signals_df.index = rolling_z_score_df.index
signals_df

In [ ]:
signals_df = signals_df.reindex(merged_df.index)

### Positions

In [ ]:
position_df = pd.DataFrame(index=signals_df.index)

for col in signals_df.columns:
    
    current_position = 0
    positions = []
    
    for signal in signals_df[col]:
        
        if signal == 1:
            current_position = 1
            
        elif signal == -1:
            current_position = -1
            
        elif signal == 0:
            current_position = 0  # EXIT must reset
        
        positions.append(current_position)
    
    position_df[col] = positions

In [ ]:
returns_df = merged_df.pct_change().fillna(0)

In [ ]:
position_df

### PnL

In [ ]:
pnl_df = pd.DataFrame(index=position_df.index)

In [ ]:
for col in position_df.columns:
    
    s1, s2 = col.split("_")
    beta_val = hedge_ratio[s1][s2]
    pnl_df[col] = position_df[col] * (returns_df[s1] - beta_val * returns_df[s2])

pnl_df

### Considering all the cointegrated pairs

In [ ]:
portfolio_returns = pnl_df.mean(axis=1)
portfolio_returns

In [ ]:
cumulative_returns = (1 + portfolio_returns).cumprod()
cumulative_returns

In [ ]:
sharpe = (portfolio_returns.mean() / portfolio_returns.std()) * np.sqrt(252)
print("Sharpe:", sharpe)

In [ ]:
cum_max = cumulative_returns.cummax()
drawdown = cumulative_returns / cum_max - 1

max_dd = drawdown.min()
print("Max Drawdown:", max_dd)

In [ ]:
total_return = cumulative_returns.iloc[-1] - 1
print("Total Return:", total_return)

### Considering only top 5 pairs with the lowest half life

In [ ]:
top_five_pairs = cointegrated_pairs_df.sort_values(by="Half_Life")[:5]
top_five_pairs

In [ ]:
pairs_list = []
for idx, row in top_five_pairs.iterrows():
    pairs_str = f'{row["Stock1"]}_{row["Stock2"]}'
    pairs_list.append(pairs_str)
pairs_list

In [ ]:
top_five_portfolio_returns = pnl_df[pairs_list].mean(axis=1)
top_five_portfolio_returns

In [ ]:
cumulative_returns = (1 + portfolio_returns).cumprod()
cumulative_returns

In [ ]:
sharpe = (portfolio_returns.mean() / portfolio_returns.std()) * np.sqrt(252)
print("Sharpe:", sharpe)

In [ ]:
cum_max = cumulative_returns.cummax()
drawdown = cumulative_returns / cum_max - 1

max_dd = drawdown.min()
print("Max Drawdown:", max_dd)

In [ ]:
total_return = cumulative_returns.iloc[-1] - 1
print("Total Return:", total_return)

### Returns Data

In [ ]:
training_returns = np.log(train_df / train_df.shift(1)).fillna(0)
training_returns